name: actions-ci-cd-angular-app

on:
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules # this allows for re-using node_modules caching, making builds a bit faster.
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: deploy_dist
          path: dist
  cd:
    needs: ci
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create folder
        run: mkdir ~/deploy_dist
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy_dist
          path: deploy_dist
      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          strip_components: 2
          source: deploy_dist/naturopath/*
          target: ${{ secrets.PATH }}prod
          rm: true
